# Inatengeneza kila kitu upya - graphics ile ile, lakini mfumo mpya stable 100%
admin = open('admin.html','w',encoding='utf-8')
admin.write("""<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admin - ALE TV</title>
<style>*{margin:0;padding:0;box-sizing:border-box}body{background:#000;color:#fff;font-family:sans-serif;padding:10px;padding-bottom:30px}.top{display:flex;justify-content:space-between;align-items:center;padding:12px 5px}.top b{color:#00ff88;font-size:18px}.top b span{color:#aaa;font-size:10px;display:block;font-weight:400}.live-dot{color:#00ff88;font-size:11px}.card{background:linear-gradient(145deg,#0a1a0a,#081408);border:1px solid #1a3a1a;border-radius:18px;padding:14px;margin-bottom:12px}.ksh{color:#c8ff00;font-size:32px;font-weight:900}.small{font-size:10px;opacity:.5;margin-top:4px}.section-title{color:#c8ff00;font-size:12px;font-weight:900;margin:18px 0 10px 0}.inputs{display:flex;flex-direction:column;gap:10px}.inputs input{background:#111;border:1px solid #2a2a2a;border-radius:24px;padding:14px 16px;color:#fff;outline:none;width:100%}.btn-weka{background:#c8ff00;color:#000;border:none;padding:15px;border-radius:24px;font-weight:900;font-size:14px;width:100%}.playlist-item{background:#111;border:1px solid #222;border-radius:14px;padding:12px;margin-bottom:8px;display:flex;justify-content:space-between;align-items:center}.btn-small{border:none;padding:6px 10px;border-radius:8px;font-weight:800;font-size:10px}.live{background:#00ff88;color:#000}.remove{background:#ff3333;color:#fff}.badge-now{background:#ff0033;color:#fff;padding:3px 8px;border-radius:8px;font-size:8px;font-weight:900}.studio{border:2px solid #00ff88;border-radius:18px;padding:16px;margin-top:15px;text-align:center;background:linear-gradient(145deg,#0a1a0a,#000)}</style></head><body>
<div class="top"><div style="display:flex;gap:8px;align-items:center"><div style="background:#00ff88;padding:6px;border-radius:8px">📺</div><b>ALE TV KE LIVE<span>KENYAN TV STATION • ADMIN PANEL</span></b></div><div class="live-dot">● LIVE</div></div>
<div class="card"><div style="color:#aaa;font-size:11px">🏦 TILL 3624692</div><div class="ksh">KSh 362,469.20</div><div class="small">Today +KSh 12,450 ▲ +3.6%</div></div>
<div class="section-title">≡ PLAYLIST - YouTube Pekee (Stable)</div>
<div class="inputs"><input id="vTitle" placeholder="Jina la video"><input id="vUrl" placeholder="YouTube link https://..."><button class="btn-weka" onclick="addVideo()">+ Weka Online - HAIKATIKI</button></div>
<div id="plist" style="margin-top:12px"></div>
<div class="studio"><div style="color:#ff4444;font-weight:900;font-size:12px">STUDIO STATUS</div><div style="color:#00ff88;font-size:11px;margin:8px 0">● LIVE - Stable System</div><a href="index.html" target="_blank" style="display:block;background:#00ff88;color:#000;padding:14px;border-radius:24px;font-weight:900;text-decoration:none;margin-top:8px">📺 ONA TV - Fungua Tab Mpya Hapa</a></div>
<script>
let state={playlist:[]};
function getYtId(url){if(!url)return'';url=url.trim();if(url.includes('youtu.be/'))return url.split('youtu.be/')[1].split('?')[0].split('&')[0];try{let u=new URL(url);if(u.searchParams.get('v'))return u.searchParams.get('v');if(url.includes('/shorts/'))return url.split('/shorts/')[1].split('?')[0];}catch(e){let m=url.match(/v=([^&]+)/);if(m)return m[1];}return'';}
function load(){try{let s=localStorage.getItem('aletv_state_v2');if(s)state=JSON.parse(s);}catch{}render();}
function save(){localStorage.setItem('aletv_state_v2',JSON.stringify(state));}
function addVideo(){let t=document.getElementById('vTitle').value.trim();let u=document.getElementById('vUrl').value.trim();if(!u){alert('Weka YouTube link mkuu!');return;}let id=getYtId(u);if(!id){alert('Link si ya YouTube! Weka https://www.youtube.com/watch?v=...');return;}if(!t)t='YouTube - '+id;let vid={id:Date.now(),title:t,url:u,ytid:id,status:'next'};state.playlist.push(vid);let live=null;try{live=JSON.parse(localStorage.getItem('aletv_live_now')||'null')}catch{}if(!live){vid.status='now';localStorage.setItem('aletv_live_now',JSON.stringify(vid));}save();render();document.getElementById('vTitle').value='';document.getElementById('vUrl').value='';alert('✅ Imewekwa! Sasa bonyeza Move to Live');}
function moveToLive(id){let v=state.playlist.find(p=>p.id===id);if(!v)return;state.playlist.forEach(p=>{if(p.status==='now')p.status='next';});v.status='now';localStorage.setItem('aletv_live_now',JSON.stringify(v));save();render();}
function removeVideo(id){let wasLive=false;try{let l=JSON.parse(localStorage.getItem('aletv_live_now')||'null');if(l&&l.id===id)wasLive=true;}catch{}state.playlist=state.playlist.filter(p=>p.id!==id);if(wasLive){localStorage.removeItem('aletv_live_now');if(state.playlist.length>0){let n=state.playlist[0];n.status='now';localStorage.setItem('aletv_live_now',JSON.stringify(n));}}save();render();}
function render(){let c=document.getElementById('plist');if(state.playlist.length===0){c.innerHTML='<div style="text-align:center;opacity:.4;padding:20px">Hakuna video bado - weka YouTube link juu</div>';return;}c.innerHTML=state.playlist.map(v=>{let right=v.status==='now'?`<span class="badge-now">NOW PLAYING</span><button class="btn-small remove" onclick="removeVideo(${v.id})">X</button>`:`<button class="btn-small live" onclick="moveToLive(${v.id})">Move to Live</button><button class="btn-small remove" onclick="removeVideo(${v.id})" style="margin-left:4px">X</button>`;return `<div class="playlist-item"><div><div style="font-size:12px;font-weight:700">${v.title}</div><div style="font-size:10px;opacity:.5">YouTube • ${v.ytid} • ${v.status}</div></div><div style="display:flex;gap:5px;align-items:center">${right}</div></div>`;}).join('');}
load();
</script></body></html>""")
print("✅ admin.html iko sawa - graphics ile ile!")

idx=open('index.html','w',encoding='utf-8')
idx.write("""<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ALE TV KE LIVE</title>
<style>*{margin:0;padding:0;box-sizing:border-box}body{background:#000;color:#fff;font-family:sans-serif}header{background:#0f1a0f;padding:12px 15px;display:flex;justify-content:space-between;position:sticky;top:0;z-index:50}#playerWrap{position:sticky;top:45px;z-index:40;background:#000;width:100%;aspect-ratio:16/9}#player{width:100%;height:100%;background:#000;position:relative}#player iframe{width:100%;height:100%;border:0;position:absolute;top:0;left:0}.info{padding:15px;background:#0a0a0a}.btn-join{background:#00ff88;color:#000;border:none;padding:14px;width:100%;border-radius:25px;font-weight:900;margin-top:12px}</style></head><body>
<header><b>ALE TV KE LIVE</b><span style="color:#00ff88;font-size:12px">TILL 3624692</span></header>
<div id="playerWrap"><div id="player"><div id="msg" style="color:#888;text-align:center;padding:40px">📺 Hakuna video - Nenda Admin weka YouTube link</div><iframe id="yt" style="display:none" allowfullscreen allow="autoplay; encrypted-media"></iframe></div></div>
<div class="info"><h2 id="title">Karibu ALE TV</h2><div id="nowPlaying" style="font-size:12px;opacity:.7;margin-top:5px">System mpya - haikatiki</div></div>
<script>
function getYtId(url){if(!url)return'';url=url.trim();if(url.includes('youtu.be/'))return url.split('youtu.be/')[1].split('?')[0].split('&')[0];try{let u=new URL(url);if(u.searchParams.get('v'))return u.searchParams.get('v');}catch(e){let m=url.match(/v=([^&]+)/);if(m)return m[1];}return'';}
function loadTV(){let cur=null;try{cur=JSON.parse(localStorage.getItem('aletv_live_now')||'null')}catch{}let state=null;try{state=JSON.parse(localStorage.getItem('aletv_state_v2')||'null')}catch{}if(!cur&&state&&state.playlist&&state.playlist.length>0)cur=state.playlist.find(p=>p.status==='now')||state.playlist[0];let msg=document.getElementById('msg'),yt=document.getElementById('yt');if(!cur){msg.innerHTML='📺 Hakuna video<br><span style="font-size:11px">Nenda Admin: localhost:8081/admin.html</span>';msg.style.display='block';yt.style.display='none';return;}document.getElementById('title').innerText=cur.title;document.getElementById('nowPlaying').innerText=cur.title;let id=cur.ytid||getYtId(cur.url);if(!id){msg.innerHTML='⚠️ Link sio sahihi';msg.style.display='block';yt.style.display='none';return;}msg.style.display='none';yt.src='https://www.youtube.com/embed/'+id+'?autoplay=1&playsinline=1&rel=0&modestbranding=1';yt.style.display='block';}
loadTV();setInterval(loadTV,3000);
</script></body></html>""")
print("✅ index.html iko sawa - haikatiki!")
print("\n✅ MFUMO MPYA TAYARI! Fungua localhost:8081/admin.html")
